name: Deploy to K8s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl get pods -l app=eshop-web
          kubectl get services